# Unique project key
sonar.projectKey=random-advice-generator
sonar.projectName=random-advice-generator
sonar.projectVersion=1.0
sonar.token=squ_90b6f6ffda4e8b778643fc2694434063ad01466f

# Path to source code
sonar.sources=src

# Exclude build files and dependencies
sonar.exclusions=**/node_modules/**, **/build/**

# Language
sonar.language=js

# Encoding
sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
sonar.login=squ_d18438a5febb8f74aeb9147b84da96c8c33bb56b

# Optional: Tests folder if any
# sonar.tests=tests
# sonar.test.inclusions=**/*.test.js
